name: CI
on: [push]
jobs:
  standard-checks:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2

    - name: Install packages
      run: npm ci
    - name: Run ESlint
      run: npm run ci:lint
    - name: Bundle and Output
      run: npm run build
    - name: Lighthouse Benchmarks
      run: npm run ci:lighthouse